# Don't print a new line at the start of the prompt
add_newline = false

format = "$cmd_duration$status$character$directory$git_branch$git_status"

# Replace the "❯" symbol in the prompt with "➜"
[character]
error_symbol = "[➜](bold red)"
success_symbol = "[➜](bold green)"

[package]
disabled = true

[cmd_duration]
show_milliseconds = true
format = "\n[$duration]($style)\n"

[status]
disabled = false
symbol = ""

